### PR TITLE
Updated description of required Maven version

### PR DESCRIPTION
**Pull request by bennetelli**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
At some point I know I tried using Maven 3.2.1 and it failed.  I'm not sure if it still fails with 3.2.1 or not.

Without testing every minor version between 3.1.0 and 3.2.5, it's safer for us to specify a minimum of 3.2.5

**Comment by bobmcwhirter** [comment]
I think I updated a README (on the primary repo? maybe -examples) saying
3.2.5.  We should consistently put it everywhere of course.

**Comment by bennetelli** [comment]
Hi Ken,

okay. Makes sense. 

There is another thing,  I just found an error in the MSA Day - WildFly-swarm keynote and pdf slides (https://github.com/wildfly-swarm/wildfly-swarm-presentations)
in slide #20 which is about Specifying the main class. The mainClass XML attribute closes with an addClasspath one instead of a </mainClass>

Tried to fix it and send a pull request, but  this snippet is a picture :/

best regards,
Bennet

**Comment by kenfinnigan** [comment]
@bobmcwhirter, I think it is consistent now. I don't think the website mentions a version, but not sure it needs to. I know a version is mentioned in User Guide, and on main repo readme.

@bennetelli, thanks for noticing the error in the presentation.  Could you file an issue in JIRA (https://issues.jboss.org/browse/SWARM) ?

Thanks
Ken

**Comment by bennetelli** [comment]
done.

**Pull request closed without merging**
