### PR TITLE
Enhance plugin to be usable as integration test goal

### PR DESCRIPTION
**Pull request by thomasmey**
E.g.
            &lt;plugin&gt;
                &lt;groupId&gt;org.wildfly.swarm&lt;/groupId&gt;
                &lt;artifactId&gt;wildfly-swarm-plugin&lt;/artifactId&gt;
                &lt;version&gt;${wildfly-swarm.version}&lt;/version&gt;
                &lt;configuration&gt;
                    &lt;mainClass&gt;de.m3y3r.cloud.App&lt;/mainClass&gt;
                &lt;/configuration&gt;
                &lt;executions&gt;
                    &lt;execution&gt;
                        &lt;id&gt;package&lt;/id&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;package&lt;/goal&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                    &lt;execution&gt;
                        &lt;id&gt;run&lt;/id&gt;
                        &lt;phase&gt;pre-integration-test&lt;/phase&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;run&lt;/goal&gt;
                        &lt;/goals&gt;
                        &lt;configuration&gt;
                            &lt;environmentFile&gt;${project.build.testResources[0].directory}/integration-test.env&lt;/environmentFile&gt;
                            &lt;waitForProcess&gt;false&lt;/waitForProcess&gt;
                        &lt;/configuration&gt;
                    &lt;/execution&gt;
                &lt;/executions&gt;
            &lt;/plugin&gt;

So the goal "run" can be used as pre-integration test, and in the lifecycle intergration-test you can then use failsafe plugin to run your tests.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
I think the integ-test bits are good. Can you explain the env-vars bits?
Properties don't suffice?

And if env-vars are useful, alternatively specify them directly in the Pom

## (like props) in addition to an external file?

Sent from my iPhone

On Nov 15, 2015, at 5:21 AM, thomasmey notifications@github.com wrote:

E.g.

org.wildfly.swarm
wildfly-swarm-plugin
${wildfly-swarm.version}

de.m3y3r.cloud.App

package

package

run
pre-integration-test

run

${project.build.testResources[0].directory}/integration-test.env
false

So the goal "run" can be used as pre-integration test, and in the lifecycle

## intergration-test you can then use failsafe plugin to run your tests.

You can view, comment on, or merge this pull request online at:

  https://github.com/wildfly-swarm/wildfly-swarm/pull/160
Commit Summary
- Add support for custom environment variables
- Add support to not wait for created process, so the plugin goal can be
  used

File Changes
- _M_ plugin/src/main/java/org/wildfly/swarm/plugin/maven/RunMojo.java
  https://github.com/wildfly-swarm/wildfly-swarm/pull/160/files#diff-0
  (49)

Patch Links:
- https://github.com/wildfly-swarm/wildfly-swarm/pull/160.patch
- https://github.com/wildfly-swarm/wildfly-swarm/pull/160.diff

—
Reply to this email directly or view it on GitHub
https://github.com/wildfly-swarm/wildfly-swarm/pull/160.

**Comment by thomasmey** [comment]
Hi,
I want to install my wildfly-swarm application into a cloud foundry environment and there are some environment variables set by CF and I want to emulate these via the said env file.

See also:
https://docs-runpivotal-production.cfapps.io/devguide/deploy-apps/environment-variable.html

As the VCAP_SERVICE file also contains username and password for database connections I don't want to include these in the pom.xml but in an external file, so I can commit the pom.xml but not the environment file. What do you think about this?

with kind regards
thomas

**Comment by bobmcwhirter** [comment]
Makes sense. Can you add the ability to also specify env cars in the POM
(along with outboard file as you have)?  I'll be happy to merge that.

## 

Sent from my iPhone

On Nov 15, 2015, at 3:43 PM, thomasmey notifications@github.com wrote:

Hi,
I want to install my wildfly-swarm application into a cloud foundry
environment and there are some environment variables set by CF and I want
to emulate these via the said env file.

See also:
https://docs-runpivotal-production.cfapps.io/devguide/deploy-apps/environment-variable.html

As the VCAP_SERVICE file also contains username and password for database
connections I don't want to include these in the pom.xml but in an external
file, so I can commit the pom.xml but not the environment file. What do you
think about this?

with kind regards
thomas

**Comment by thomasmey** [comment]
I'm working on it!

**Comment by thomasmey** [comment]
please have a look at my updated branch.

**Comment by bobmcwhirter** [comment]
I’ll take a look at this tomorrow morning.  Thanks for your work on it!

**Pull request merged**
