### PR TITLE
Creating initial webservices fraction.

### PR DESCRIPTION
**Pull request by johnament**
Not necessarily for merging yet, but feedback strongly encouraged.

I have a need for a SOAP API, and wanted to start bringing this in.  I still need the model node configuration and tests.

### CODE REVIEW

**Comment by johnament** [comment]
So, one problem I'm seeing

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.swarm:wildfly-swarm-fraction-plugin:1.0.0.Alpha3:generate (default) on project wildfly-swarm-webservices: Unable to locate required module: org.wildfly.swarm.webservices:main -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wildfly.swarm:wildfly-swarm-fraction-plugin:1.0.0.Alpha3:generate (default) on project wildfly-swarm-webservices: Unable to locate required module: org.wildfly.swarm.webservices:main
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Unable to locate required module: org.wildfly.swarm.webservices:main
    at org.wildfly.swarm.plugin.NewGenerateMojo.locateFillModules(NewGenerateMojo.java:113)
    at org.wildfly.swarm.plugin.NewGenerateMojo.execute(NewGenerateMojo.java:90)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
```

I'm not sure what the issue is with this yet.

**Comment by bobmcwhirter** [comment]
That stack looks like you might need a feature-pack (or several) added to your pom.xml.

**Comment by bobmcwhirter** [comment]
But you have them all, so I'm not sure...

**Comment by kenfinnigan** [comment]
@johnament, I think the issue is that https://github.com/johnament/wildfly-swarm/blob/master/api/webservices/src/main/resources/modules/org/wildfly/swarm/webservices.main/module.xml has a folder of `webservices.main` instead of two folders representing `webservices/main`

**Comment by johnament** [comment]
Damn you intellij! Thanks @kenfinnigan Let me fix that up.

**Comment by tarilabs** [comment]
Just to say thank you for having this PR recorded, even if open; after I found this, I understand why webservice was not working while trying out swarm today =)

**Comment by johnament** [comment]
Yeah, I hope to complete this soon.

**Comment by johnament** [comment]
Closing since this is way out of date.

**Comment by tarilabs** [comment]
Okay, but pardon the stupid question, is there a way now to enable javax.jws.@WebService in wildfly swarm by other means, please?

**Comment by johnament** [comment]
@tarilabs I added a new PR based on the current codebase.  The changes were too substantial to warrant a rebase, I left this to the side for too long.  https://github.com/wildfly-swarm/wildfly-swarm/pull/150

It deploys but doesn't yet run w/ webservices enabled.

**Comment by tarilabs** [comment]
Many thanks for the clarification @johnament

**Pull request closed without merging**
