### PR TITLE
The wildflySwarmNode attribute should be in the metaData of the Logst…

### PR DESCRIPTION
**Pull request by jamezp**
…ashFormatter.

### CODE REVIEW

**Comment by jamezp** [comment]
I didn't want to merge this without knowing whether or no it's okay to add module dependencies here or if the `LoggingFraction` should be updated to support an option for named formatters.

**Comment by bobmcwhirter** [comment]
I don't grok the question?

## 

Sent from my iPhone

On Nov 10, 2015, at 6:26 PM, James R. Perkins notifications@github.com
wrote:

I didn't want to merge this without knowing whether or no it's okay to add
module dependencies here or if the LoggingFraction should be updated to
support an option for named formatters.

**Comment by jamezp** [comment]
Sorry. In order to make this work I had to add a module dependency on the `LogstashFraction` of `org.wildfly.swarm.configuration`. A `CustomHandler` needs to be built so the `CustomHandler.namedFormatter()` can be used. I wasn't sure if we should instead change the `LoggingFraction` to allow a `CustomFormatter` to be added instead of adding a dependency to the `LogstashFraction`.

Something like `LoggingFraction.customHandlerWithNamedFormatter()`. I don't love that name though :)

**Comment by bobmcwhirter** [comment]
Ah. That dependency is always okay.

## 

Sent from my iPhone

On Nov 10, 2015, at 7:53 PM, James R. Perkins notifications@github.com
wrote:

Sorry. In order to make this work I had to add a module dependency on the
LogstashFraction of org.wildfly.swarm.configuration. A CustomHandler needs
to be built so the CustomHandler.namedFormatter() can be used. I wasn't
sure if we should instead change the LoggingFraction to allow a
CustomFormatter to be added instead of adding a dependency to the
LogstashFraction.

Something like LoggingFraction.customHandlerWithNamedFormatter(). I don't
love that name though :)

**Comment by jamezp** [comment]
Excellent, I'll merge it then. Thanks!

**Comment by bobmcwhirter** [comment]
Thank you!

## 

Sent from my iPhone

On Nov 10, 2015, at 7:55 PM, James R. Perkins notifications@github.com
wrote:

Excellent, I'll merge it then. Thanks!

**Pull request merged**
