### PR TITLE
Minor changes and refactor

### PR DESCRIPTION
**Pull request by jamezp**
This should work, but I wasn't able to get it to work. This was due to the version resolution in the `ModuleXmlParser`. I'm not sure if we should hold off on this PR or not. I think some work needs to be done to switch to using the `*-build` dependencies rather than the `*-feature-pack`. The provisioned, `*-build` will include the versions in the `module.xml` files.

Anyway, I thought I'd at least open this PR to open the discussion.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
I agree that having the versions in the module.xml would be great.  Considering how we populate the m2repo/ now with a user's own dependencies also (for the APP:dependencies module), there is a chance of finding the wrong version from a module.xml if there's more than one, since we currently do a first-match-wins thing.

**Comment by jamezp** [comment]
Yeah that was my issue with picketbox. I should try it on my mac to see if that works. I tried to get it to work with the `wildfly-build`, but for some reason all the dependencies weren't copied over. I'll try to look into when I get some more time.

**Comment by bobmcwhirter** [comment]
I did recently muck about with the fraction plugin in terms of adding a wildfly-swarm-feature-pack.gav and a wildfly-swarm-fraction.gav file to the fractional .jars.  I may have screwed something up there, or have some mvn dependencies between the fractions incorrect.

**Comment by bobmcwhirter** [comment]
I had to change

```
        Files.createDirectories(dest);
```

to 

```
        Files.createDirectories(dest.getParent());
```

but otherwise it merged cleanly and works locally.

Merged!

**Pull request merged**
