### PR TITLE
Add a debugBootstrap flag to Container ctor

### PR DESCRIPTION
**Pull request by starksm64**
I created a new Container(boolean debugBootstrap) ctor that configures the org.jboss.modules.Module module logger to dump the bootstrap phase before any logging manager is loaded to System.out. This is the same behavior change I submitted in the https://issues.jboss.org/browse/MODULES-210 feature request that add a -debugConsole option.

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
Maybe Systerm.err instead of .out?

**Comment by bobmcwhirter** [comment]
BTW- just invited you to the team. Feel free to commit and push whatever you think is good. We aren't heavy on PR process like WildFly itself. 

Welcome aboard!

**Comment by starksm64** [comment]
System.err is fine, so I'll merge that, thanks.

**Comment by kenfinnigan** [comment]
This has been merged. Closing

**Pull request closed without merging**
