### PR TITLE
Initial webservices fraction

### PR DESCRIPTION
**Pull request by johnament**
This works a bit better, can get an app deployed, but no soap endpoints generated yet :-(

### CODE REVIEW

**Comment by johnament** [comment]
This almost works, I can see the webservices bootstrap when launching the server.  However, I get this error

```
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:154)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
    at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.jboss.as.webservices.deployers.deployment.DeploymentModelBuilderJAXWS_EJB.build(DeploymentModelBuilderJAXWS_EJB.java:62)
    at org.jboss.as.webservices.deployers.deployment.AbstractDeploymentModelBuilder.newDeploymentModel(AbstractDeploymentModelBuilder.java:95)
    at org.jboss.as.webservices.deployers.deployment.WSDeploymentBuilder.build(WSDeploymentBuilder.java:65)
    at org.jboss.as.webservices.deployers.WSModelDeploymentProcessor.internalDeploy(WSModelDeploymentProcessor.java:44)
    at org.jboss.as.webservices.deployers.TCCLDeploymentProcessor.deploy(TCCLDeploymentProcessor.java:43)
    at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:147)
    ... 5 more
```

I'm wondering if @asoldano might have any ideas, otherwise I'm going to keep poking at it.

**Comment by johnament** [comment]
@kenfinnigan just wondering if you have any tips for debugging swarm fractions? this NPE is mind bottling.

**Comment by kenfinnigan** [comment]
@johnament sometimes it's necessary to have WildFly source in an IDE connect to a debug instance so you can step through those kind of issues.

Messy but useful

**Comment by johnament** [comment]
@kenfinnigan i'll try to catch you guys on IRC at some point.  i tried setting up a main method that does the execution, but that doesn't seem to run

**Comment by jamesnetherton** [comment]
At a guess I'd say you're missing some config for the WS subsystem configuration in your WebServicesConfiguration class. Specifically the 'endpoint-config' part.

**Comment by bobmcwhirter** [comment]
Let us add WS to the config api and it'll be easier to get the setup going.

## 

Sent from my iPhone

On Nov 6, 2015, at 8:54 AM, James Netherton notifications@github.com
wrote:

At a guess I'd say you're missing some config for the WS subsystem
configuration in your WebServicesConfiguration class. Specifically the
'endpoint-config' part.

**Comment by heiko-braun** [comment]
It's merged but we need to update swarm itself to include the new config-api version: https://github.com/wildfly-swarm/wildfly-config-api/pull/10

**Comment by johnament** [comment]
Right, right now I'm pointing to a snapshot version of the config api w/ WS enabled.   Once you cut a release w/ the new one should be good, but I was running into some jgroups dependency issues.

**Comment by johnament** [comment]
Ok, that was it.  I forgot in my original code I had a default setup for this, found that EJB did something similar and followed that pattern.

Now...

```
2015-11-06 20:02:04,464 INFO  [org.jboss.ws.cxf.metadata] (MSC service thread 1-3) JBWS024061: Adding service endpoint metadata: id=SOAPServer
 address=http://localhost:8080/SOAPServer
 implementor=soap.SOAPServer
 serviceName={http://soap/}SOAPServerService
 portName={http://soap/}SOAPServerPort
 annotationWsdlLocation=null
 wsdlLocationOverride=null
 mtomEnabled=false
```

Swarm is cleaner with SOAP :-X

(Horrible joke)

**Comment by bobmcwhirter** [comment]
I'll push a release of config-api on Monday.

**Comment by johnament** [comment]
Sounds good.  Let me know if you want me to squash this together after you cut the release.  Also, I'm not sure if there's a better way to test the container right now.  It required manual inspection.

**Comment by asoldano** [comment]
I was on PTO. I assume you're fine/done here, but if you need anything more from me, just ask.

**Comment by tarilabs** [comment]
Just to say thank you for this and #153 , I'm trying out Swarm with webservices :+1:

**Pull request closed without merging**
