### PR TITLE
SWARM-288: Upgrade to Wildfly 10.0.0.Final

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Does config API need to be updated? Or it will work with newer WildFly?

Also, do msc or javax.sql versions need to be updated to match?

**Comment by gastaldi** [comment]
Good questions. I haven't checked that TBH. But hey, the tests passed :)

**Comment by bobmcwhirter** [comment]
I merged this but we should double check. Config API is probably fine.

## 

Sent from my iPhone

On Jan 30, 2016, at 10:30 AM, George Gastaldi notifications@github.com
wrote:

Good questions. I haven't checked that TBH. But hey, the tests passed :)

**Comment by gastaldi** [comment]
For your second question, as of https://github.com/jboss-msc/jboss-msc, 1.2.6.Final is the latest version (the same used in Swarm). 

Checking javax.sql version now

**Comment by gastaldi** [comment]
As of http://mvnrepository.com/artifact/org.jboss.spec.javax.sql/jboss-javax-sql-api_7.0_spec, 2.0.0.Final is the latest version, so it´s ok.

**Comment by kenfinnigan** [comment]
Thanks for checking George!

We've been bitten by that in the past :-)

Ken

**Comment by bobmcwhirter** [comment]
Maybe again.

https://projectodd.ci.cloudbees.com/job/wildfly-swarm-examples/281/

## 

Sent from my iPhone

On Jan 30, 2016, at 11:24 AM, Ken Finnigan notifications@github.com wrote:

Thanks for checking George!

We've been bitten by that in the past :-)

Ken

Sent from my iPhone

**Comment by bobmcwhirter** [comment]
Root problem:

Caused by: java.lang.ClassCastException: org.h2.Driver cannot be cast to
javax.sql.DataSource

## 

Sent from my iPhone

On Jan 30, 2016, at 11:24 AM, Ken Finnigan notifications@github.com wrote:

Thanks for checking George!

We've been bitten by that in the past :-)

Ken

Sent from my iPhone

**Comment by bobmcwhirter** [comment]
Ya kicked another build. Same failure.

**Comment by kenfinnigan** [comment]
Will take a look tonight

Seems reminiscent of some errors we had when switching to config API

**Comment by bobmcwhirter** [comment]
Maybe try rebasing config API. I can publish first thing Monday if we need
a rev of it against 10.Final.

## 

Sent from my iPhone

On Jan 30, 2016, at 4:10 PM, Ken Finnigan notifications@github.com wrote:

Will take a look tonight

Seems reminiscent of some errors we had when switching to config API

**Comment by bobmcwhirter** [comment]
Any luck?

**Comment by helio-frota** [comment]
Hi, i'm looking into it too.

**Comment by kenfinnigan** [comment]
Looking now.

I don't think it's a config-api issue.

The exception is:

2016-01-31 09:38:20,098 WARN
 [org.jboss.jca.core.connectionmanager.pool.strategy.OnePool](default
task-1) IJ000604: Throwable while attempting to get a new connection: null:
javax.resource.ResourceException: IJ031084: Unable to create connection
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:343)
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getLocalManagedConnection(LocalManagedConnectionFactory.java:350)
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createManagedConnection(LocalManagedConnectionFactory.java:285)
at
org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.createConnectionEventListener(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:1319)
at
org.jboss.jca.core.connectionmanager.pool.mcp.SemaphoreConcurrentLinkedDequeManagedConnectionPool.getConnection(SemaphoreConcurrentLinkedDequeManagedConnectionPool.java:496)
at
org.jboss.jca.core.connectionmanager.pool.AbstractPool.getSimpleConnection(AbstractPool.java:626)
at
org.jboss.jca.core.connectionmanager.pool.AbstractPool.getConnection(AbstractPool.java:598)
at
org.jboss.jca.core.connectionmanager.AbstractConnectionManager.getManagedConnection(AbstractConnectionManager.java:590)
at
org.jboss.jca.core.connectionmanager.tx.TxConnectionManagerImpl.getManagedConnection(TxConnectionManagerImpl.java:429)
at
org.jboss.jca.core.connectionmanager.AbstractConnectionManager.allocateConnection(AbstractConnectionManager.java:747)
at
org.jboss.jca.adapters.jdbc.WrapperDataSource.getConnection(WrapperDataSource.java:138)
at
org.jboss.as.connector.subsystems.datasources.WildFlyDataSource.getConnection(WildFlyDataSource.java:66)
at
org.wildfly.swarm.examples.ds.subsystem.MyResource.get(MyResource.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
at
org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
at
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
at
org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
at
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
at
org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
at
org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
at
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
at
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at
io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
at
io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
at
io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
at
org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
at
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at
io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
at
io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
at
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at
io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
at
io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
at
io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
at
io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
at
io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
at
io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
at
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at
org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
at
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at
io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
at
io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
at
io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
at
io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
at
io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: javax.resource.ResourceException: IJ031089: Failed to load
datasource: org.h2.Driver
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getDataSource(LocalManagedConnectionFactory.java:650)
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:311)
... 53 more
Caused by: java.lang.ClassCastException: org.h2.Driver cannot be cast to
javax.sql.DataSource
at
org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getDataSource(LocalManagedConnectionFactory.java:633)
... 54 more

I think it's a bug in WF itself

Ken

**Comment by bobmcwhirter** [comment]
Does WildFly itself boot with the equivalent in standalone.xml? Would be a strange but for a Final.

**Comment by heiko-braun** [comment]
A driver is no datasource, is it? Did we mess up those settings in the config api or example?

**Comment by bobmcwhirter** [comment]
It worked with CR5 and rebasing to .Final broke it.

## 

Sent from my iPhone

On Jan 31, 2016, at 11:01 AM, Heiko Braun notifications@github.com wrote:

A driver is no datasource, is it? Did we mess up those settings in the
config api or example?

**Comment by heiko-braun** [comment]
Maybe the strings for both attributes got replaced by mistake? On the phone right now so i cannot look myself into the code

**Comment by bobmcwhirter** [comment]
Ken and Helio were investigating. If no luck I'll look in the morning.

## 

Sent from my iPhone

On Jan 31, 2016, at 11:02 AM, Heiko Braun notifications@github.com wrote:

Maybe the strings for both attributes got replaced by mistake? On the phone
right now so i cannot look myself into the code

**Comment by helio-frota** [comment]
weird because on wildfly 10 final it is working...
The generated standalone is:

```
<datasource jndi-name="java:jboss/datasources/ExampleDS" pool-name="ExampleDS" enabled="true" use-java-context="true">
                    <connection-url>jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE</connection-url>
                    <driver>h2</driver>
                    <security>
                        <user-name>sa</user-name>
                        <password>sa</password>
                    </security>
                </datasource>
                <xa-datasource jndi-name="java:/H2XADS" pool-name="H2XADS" enabled="true" use-ccm="true">
                    <xa-datasource-property name="URL">
                        jdbc:h2:mem:test
                    </xa-datasource-property>
                    <driver>h2</driver>
                    <security>
                        <user-name>sa</user-name>
                        <password>sa</password>
                    </security>
                    <validation>
                        <background-validation>false</background-validation>
                    </validation>
                </xa-datasource>
                <drivers>
                    <driver name="h2" module="com.h2database.h2">
                        <xa-datasource-class>org.h2.jdbcx.JdbcDataSource</xa-datasource-class>
                    </driver>
                </drivers>
```

screenshot:

**Comment by helio-frota** [comment]
build ok here...but I'm double checking...

**Comment by kenfinnigan** [comment]
Found the issue.

Between IronJacamar 1.3.1 and 1.3.2 (ala WF CR5 and Final), they fixed a
bug whereby DataSource class name was not being set properly.

In our examples we set driverDatasourceClass() in main(), which worked
before because the DataSource class wasn't being set.

Now it's being set and causing an issue because the class we're setting is
not a DataSource class, only a Driver one.

Fix for examples coming shortly

Ken

**Comment by helio-frota** [comment]
@kenfinnigan 
Exactly, I commented lines the build passed 

```
//d.driver Datasource classname ("org.h2.Driver"); //d.xaDatasourceClass("org.h2.jdbcx.JdbcDataSource ");
```

**Comment by helio-frota** [comment]
further information

another failure :

[INFO] WildFly Swarm Examples: JPA .war ................... FAILURE [02:07 min]

Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set

**Comment by helio-frota** [comment]
I found a weird behavior...
Theres no h2 module on connector-modules-1.0.0.Alpha7-SNAPSHOT.jar

```
Caused by: javax.resource.ResourceException: IJ031089: Failed to load datasource: org.h2.driver
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getDataSource(LocalManagedConnectionFactory.java:650)
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:311)
    ... 36 more
Caused by: java.lang.ClassNotFoundException: org.h2.driver from [Module "com.h2database.h2:main" from BootModuleLoader@5bc79255 for finders [BootstrapClasspathModuleFinder, BootstrapModuleFinder(org.wildfly.swarm.bootstrap:main), ClasspathModuleFinder, ApplicationModuleFinder(swarm.application:main)]]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.getDataSource(LocalManagedConnectionFactory.java:632)
    ... 37 more
```

```
jar tf connector-modules-1.0.0.Alpha7-SNAPSHOT.jar
META-INF/
META-INF/MANIFEST.MF
modules/
modules/com/
modules/com/fasterxml/
modules/com/fasterxml/classmate/
modules/com/fasterxml/classmate/main/
modules/com/google/
modules/com/google/guava/
modules/com/google/guava/main/
modules/org/
modules/org/wildfly/
modules/org/wildfly/swarm/
modules/org/wildfly/swarm/connector/
modules/org/wildfly/swarm/connector/api/
modules/org/wildfly/swarm/connector/main/
modules/org/wildfly/swarm/connector/runtime/
modules/org/hibernate/
modules/org/hibernate/validator/
modules/org/hibernate/validator/main/
modules/org/jboss/
modules/org/jboss/weld/
modules/org/jboss/weld/core/
modules/org/jboss/weld/core/main/
modules/org/jboss/ironjacamar/
modules/org/jboss/ironjacamar/api/
modules/org/jboss/ironjacamar/api/main/
modules/org/jboss/ironjacamar/jdbcadapters/
modules/org/jboss/ironjacamar/jdbcadapters/main/
modules/org/jboss/ironjacamar/impl/
modules/org/jboss/ironjacamar/impl/main/
modules/org/jboss/as/
modules/org/jboss/as/connector/
modules/org/jboss/as/connector/main/
modules/org/joda/
modules/org/joda/time/
modules/org/joda/time/main/
modules/org/jsoup/
modules/org/jsoup/main/
modules/ch/
modules/ch/qos/
modules/ch/qos/cal10n/
modules/ch/qos/cal10n/main/
modules/com/fasterxml/classmate/main/module.xml
modules/com/google/guava/main/module.xml
modules/org/wildfly/swarm/connector/api/module.xml
modules/org/wildfly/swarm/connector/main/module.xml
modules/org/wildfly/swarm/connector/runtime/module.xml
modules/org/hibernate/validator/main/module.xml
modules/org/jboss/weld/core/main/module.xml
modules/org/jboss/ironjacamar/api/main/module.xml
modules/org/jboss/ironjacamar/jdbcadapters/main/module.xml
modules/org/jboss/ironjacamar/impl/main/module.xml
modules/org/jboss/as/connector/main/module.xml
modules/org/joda/time/main/module.xml
modules/org/jsoup/main/module.xml
modules/ch/qos/cal10n/main/module.xml
META-INF/maven/
META-INF/maven/org.wildfly.swarm/
META-INF/maven/org.wildfly.swarm/connector-modules/
META-INF/maven/org.wildfly.swarm/connector-modules/pom.xml
META-INF/maven/org.wildfly.swarm/connector-modules/pom.properties
META-INF/INDEX.LIST
```

**Comment by helio-frota** [comment]
I don't know if this makes sense for this problem BTW... but doing the same @kenfinnigan did on JPAFraction https://github.com/wildfly-swarm/wildfly-swarm/blob/f0c5644e5ea0d111bbf5aeb80858e00df42a639b/jpa/api/src/main/java/org/wildfly/swarm/jpa/JPAFraction.java#L48 the error changed a bit.

**Comment by gastaldi** [comment]
Any luck?

**Comment by helio-frota** [comment]
this fixes: https://github.com/wildfly-swarm/wildfly-swarm/pull/189

**Comment by helio-frota** [comment]
but we have a different error from ribbon :
https://gist.github.com/helio-frota/0a5545e404758a7ae18c
timeout

**Comment by helio-frota** [comment]
running again here was ok:

[INFO] WildFly Swarm Examples: Netflix Ribbon: Events ..... SUCCESS [  0.542 s]
[INFO] WildFly Swarm Examples: Netflix Ribbon: Time ....... SUCCESS [  0.137 s]
[INFO] WildFly Swarm Examples: Netflix Ribbon: Multi-service Test SUCCESS [ 56.989 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2016-01-31T18:43:58-03:00
[INFO] Final Memory: 70M/787M

**Comment by kenfinnigan** [comment]
Thanks for the JPA example fix Helio!

Missed that one earlier

Ken

**Comment by bobmcwhirter** [comment]
And the builds are green! Great work everyone!

**Comment by gastaldi** [comment]
:beers:

**Pull request merged**
