### PR TITLE
Make wildfly-swarm work on CloudFoundry environment

### PR DESCRIPTION
**Pull request by thomasmey**
Trying to use an wildfly-swarm Über-JAR on a cloudfoundry environment results in a crash of the application.

This is because CF unpacks the JAR file and starts the application from the unpacked directory, and sets the classpath by a given heuristic.
The same crash can be seen when you unpack the Über-JAR file locally and start the app from the unpacked directory:

$ java -cp . org.wildfly.swarm.bootstrap.Main
Exception in thread "main" java.lang.ClassNotFoundException: org.wildfly.swarm.Swarm from [Module "swarm.application:main" from BootModuleLoader@27c170f0 for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@5451c3a8, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@2626b418, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@5a07e868, org.wildfly.swarm.bootstrap.modules.ApplicationModuleFinder@76ed5528]]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
    at org.wildfly.swarm.bootstrap.Main.getMainClass(Main.java:75)
    at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
    at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)

This PR is my first try to make WFS work on CF.

But sadly I wasn't able to build and test this patch because Maven gave me some strange lookup errors:

Downloaded: http://repository.jboss.org/nexus/content/groups/public/org/apache/maven/archetype/archetype-packaging/maven-metadata.xml (383 B at 0.2 KB/sec)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.wildfly:wildfly-parent:pom:10.0.0.CR5 in google-maven-central (https://maven-central.storage.googleapis.com) @ line 795, column 19
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.wildfly.swarm:build-bom:1.0.0.Alpha6-SNAPSHOT (/home/thomas/source/wildfly-swarm/build/bom/pom.xml) has 1 error
[ERROR]     Non-resolvable import POM: Could not find artifact org.wildfly:wildfly-parent:pom:10.0.0.CR5 in google-maven-central (https://maven-central.storage.googleapis.com) @ line 795, column 19 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

So please have a look at this patch and please give some feedback what you think about this idea!

with kind regards
thomas

### CODE REVIEW

**Comment by bobmcwhirter** [comment]
This didn't pass CI, and now it's got conflicts.

I'd still like to add this functionality in, so if you could rebase, that'd be great.  Else, I'll try to manually apply them next week.

**Comment by thomasmey** [comment]
Okay, I was able to resolve the maven problems and bootstrap module builds now.

But when I try to package a wildfly-swarm app I get this error:
Unable to create -swarm.jar: Unable to load org.wildfly.swarm:bootstrap; check your dependencies

I'm not sure why. Any ideas?

**Comment by bobmcwhirter** [comment]
Somewhere in your `mvn dependency:tree` there should be
org.wildfly.swarm:bootstrap.

Normally it transitives via undertow or some other dependency.

**Comment by bobmcwhirter** [comment]
That said, are you trying the build against a private app, or one of the
-examples?

**Comment by thomasmey** [comment]
Private app.

**Comment by bobmcwhirter** [comment]
Can you gist your output from `mvn dependency:tree` and your <dependency>’s
from your pom.xml, if you can’t share the entire app?

**Comment by thomasmey** [comment]
[INFO] +- org.wildfly.swarm:wildfly-swarm-bean-validation:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |  +- org.wildfly.swarm:wildfly-swarm-container:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |  |  +- org.wildfly.swarm:wildfly-swarm-bootstrap:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |  |  |  - org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:jar:2.0.0.Final:compile
[INFO] |  |  +- org.wildfly.swarm:wildfly-swarm-container-modules:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |  |  |  - org.wildfly.swarm:config-api:jar:0.3.17:compile
[INFO] |  |  |     - org.wildfly.swarm:config-api-runtime:jar:0.3.17:compile

It's there in the tree. I did install the modified bootstrap from wildfly-swarm with mvn install locally (including this patch/commits).

Pom is here:
https://github.com/thomasmey/einkaufsliste-server/blob/master/server/pom.xml

**Comment by bobmcwhirter** [comment]
Ah, try moving to Alpha6-SNAPSHOT and using our snapshot repository.

http://repository-projectodd.forge.cloudbees.com/snapshot/

The correct (current) artifactIds are like `bootstrap` and `container` without the `wildfly-swarm-*` prefix.

Or, since you're building wildfly-swarm locally, just adjust your app's dependencies from

```
<artifactId>wildfly-swarm-bean-validation</artifactId>
```

and

```
<artifactId>wildfly-swarm-jpa</artifactId>
```

to

```
<artifactId>bean-validation<artifactId>
```

and

```
<artifactId>jpa<artifactId>
```

Same groupId of `org.wildfly.swarm`

**Comment by thomasmey** [comment]
Thanks that did the trick.

I rebuild my app and unpacked it and started it with:

$ java -cp . org.wildfly.swarm.bootstrap.Main
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:86)
    at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
    at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)
Caused by: java.lang.NoClassDefFoundError: Failed to link org/wildfly/swarm/jmx/JMXFraction (Module "org.wildfly.swarm.jmx:api" from BootModuleLoader@1e88b3c for finders [BootstrapClasspathModuleFinder, BootstrapModuleFinder(org.wildfly.swarm.bootstrap:main), ClasspathModuleFinder, ApplicationModuleFinder(swarm.application:main)]): org/wildfly/swarm/config/JMX
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446)
    at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
    at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
    at org.jboss.modules.Module.loadModuleClass(Module.java:605)
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
    at org.wildfly.swarm.jmx.runtime.JMXConfiguration.<init>(JMXConfiguration.java:29)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at java.lang.Class.newInstance(Class.java:442)
    at org.wildfly.swarm.container.runtime.RuntimeServer.loadFractionConfigurations(RuntimeServer.java:353)
    at org.wildfly.swarm.container.runtime.RuntimeServer.start(RuntimeServer.java:145)
    at org.wildfly.swarm.container.Container.start(Container.java:351)
    at de.m3y3r.cloud.App.run(App.java:109)
    at de.m3y3r.cloud.App.main(App.java:48)
    ... 7 more

It seems to boot, maybe some stale dependency error, while renaming stuff? Or is this PR still buggy?

**Comment by thomasmey** [comment]
Starting the uber-jar directly results in the same error! So this PR probably works.

**Comment by bobmcwhirter** [comment]
Okay. I'll check it out tomorrow and try to merge it before our release.
Thanks!

## 

Sent from my iPhone

On Jan 14, 2016, at 5:10 PM, thomasmey notifications@github.com wrote:

Starting the uber-jar directly results in the same error! So this PR
probably works.

**Comment by bobmcwhirter** [comment]
I needed to add a test for the wildfly-swarm.properties before blindly reading it to determine if the uberjar is exploded, but otherwise, this seems good.

I'm doing a full build against our -examples repo, but a single-build + explosion seemed to work:

https://gist.github.com/bobmcwhirter/799bac4e13b87d442d7e

**Comment by bobmcwhirter** [comment]
I've merged (with modifications) this to master/HEAD. 

Thanks!

**Comment by thomasmey** [comment]
with the current git I still get this error, when running the uber-jar:
Caused by: java.lang.NoClassDefFoundError: Failed to link org/wildfly/swarm/jmx/JMXFraction (Module "org.wildfly.swarm.jmx:api" from BootModuleLoader@544a2ea6 for finders [BootstrapClasspathModuleFinder, BootstrapModuleFinder(org.wildfly.swarm.bootstrap:main), ClasspathModuleFinder, ApplicationModuleFinder(swarm.application:main)]): org/wildfly/swarm/config/JMX

Bug or feature?

I see this in the dependency tree:
[INFO] |  - org.wildfly.swarm:weld:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |     +- org.wildfly.swarm:weld-modules:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |     |  - org.wildfly.swarm:transactions-modules:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |     |     - org.wildfly.swarm:jgroups-modules:jar:1.0.0.Alpha6-SNAPSHOT:compile
[INFO] |     |        - org.wildfly.swarm:jmx-modules:jar:1.0.0.Alpha6-SNAPSHOT:compile

**Comment by bobmcwhirter** [comment]
Probably a bug.  Can you poke around with one of the -examples projects, so
I can try to replicate?

Using the jaxrs-shrinkwrap example, things worked.  But it didn’t involve
JMX.

**Comment by thomasmey** [comment]
Will do so, but not today. 
Am 15.01.2016 9:52 nachm. schrieb Bob McWhirter notifications@github.com:Probably a bug.  Can you poke around with one of the -examples projects, so
I can try to replicate?

Using the jaxrs-shrinkwrap example, things worked.  But it didn’t involve
JMX.

**Comment by thomasmey** [comment]
Hi,

okay above error was some stale wildfly-swarm build result. I did now clean and re-install wildfly-swarm alpha7 and the container starts now correctly!

But there seems to be still another error:

Log output:
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./

2016-01-16 16:47:45,450 SEVERE [de.m3y3r.cloud.App](main) server failed: org.wildfly.swarm.container.DeploymentException: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.RuntimeException: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer
    Caused by: java.lang.ClassCastException: org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to io.undertow.websockets.jsr.ServerWebSocketContainer"}}
    at org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:132)
    at org.wildfly.swarm.container.Container.deploy(Container.java:406)
    at de.m3y3r.cloud.App.run(App.java:134)
    at de.m3y3r.cloud.App.main(App.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:86)
    at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
    at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)

any ideas?

And a remark/question regarding the CloudFoundry environment resp. wildfly-swarm:

-> the wildfly-swarm uber jar contains a spring-core*.jar file which triggers so called javabuild-pack the Spring Auto-reconfiguration Framework ()
why is the spring-core part of the uber jar? what classes are used by wildfly-swarm?
I was able to disable this framework by setting the cloudfoundry environment variable:
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: { enabled: false }

**Comment by bobmcwhirter** [comment]
That's especially weird. We don't use anything Spring that I'm aware of.

## 

Sent from my iPhone

On Jan 16, 2016, at 11:21 AM, thomasmey notifications@github.com wrote:

Hi,

okay above error was some stale wildfly-swarm build result. I did now clean
and re-install wildfly-swarm alpha7 and the container starts now correctly!

But there seems to be still another error:

Log output:
WFLYCTL0186: Services which failed to start: service
jboss.undertow.deployment.default-server.default-host./

2016-01-16 16:47:45,450 SEVERE de.m3y3r.cloud.App <main> server failed:
org.wildfly.swarm.container.DeploymentException: {"WFLYCTL0080: Failed
services" => {"jboss.undertow.deployment.default-server.default-host./" =>
"org.jboss.msc.service.StartException in service
jboss.undertow.deployment.default-server.default-host./:
java.lang.RuntimeException: java.lang.ClassCastException:
org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to
io.undertow.websockets.jsr.ServerWebSocketContainer
Caused by: java.lang.RuntimeException: java.lang.ClassCastException:
org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to
io.undertow.websockets.jsr.ServerWebSocketContainer
Caused by: java.lang.ClassCastException:
org.apache.tomcat.websocket.server.WsServerContainer cannot be cast to
io.undertow.websockets.jsr.ServerWebSocketContainer"}}
at
org.wildfly.swarm.container.runtime.RuntimeDeployer.deploy(RuntimeDeployer.java:132)
at org.wildfly.swarm.container.Container.deploy(Container.java:406)
at de.m3y3r.cloud.App.run(App.java:134)
at de.m3y3r.cloud.App.main(App.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:86)
at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)

any ideas?

And a remark/question regarding the CloudFoundry environment resp.
wildfly-swarm:

-> the wildfly-swarm uber jar contains a spring-core*.jar file which
triggers so called javabuild-pack the Spring Auto-reconfiguration Framework
()
why is the spring-core part of the uber jar? what classes are used by
wildfly-swarm?
I was able to disable this framework by setting the cloudfoundry
environment variable:
JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: { enabled: false }

**Comment by thomasmey** [comment]
oops! I found the culprit!

[DEBUG] de.m3y3r:einkaufsliste-server-server:jar:0.1.0-SNAPSHOT
[DEBUG]    org.cloudfoundry:cloudfoundry-client-lib:jar:1.1.2:compile
[DEBUG]       org.springframework:spring-webmvc:jar:4.0.5.RELEASE:compile
[DEBUG]          org.springframework:spring-beans:jar:4.0.5.RELEASE:compile
[DEBUG]          org.springframework:spring-context:jar:4.0.5.RELEASE:compile
[DEBUG]             org.springframework:spring-aop:jar:4.0.5.RELEASE:compile
[DEBUG]          org.springframework:spring-core:jar:4.0.5.RELEASE:compile
[DEBUG]          org.springframework:spring-expression:jar:4.0.5.RELEASE:compile
[DEBUG]          org.springframework:spring-web:jar:4.0.5.RELEASE:compile
[DEBUG]       org.springframework.security.oauth:spring-security-oauth2:jar:2.0.4.RELEASE:compile
[DEBUG]          org.springframework.security:spring-security-core:jar:3.2.5.RELEASE:compile
[DEBUG]             aopalliance:aopalliance:jar:1.0:compile
[DEBUG]          org.springframework.security:spring-security-config:jar:3.2.5.RELEASE:compile
[DEBUG]          org.springframework.security:spring-security-web:jar:3.2.5.RELEASE:compile
[DEBUG]          org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:compile
[DEBUG]             org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile

OMG!!!

**Pull request merged**
